version: 0.2

env:
  variables:
    # These are the names of your service directories in the 'microservices' folder
    SERVICES: "cart-service order-service product-service summary-service"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Running Maven build...
      - mvn clean install
      - echo Building and pushing Docker images...
      - |
        for service in $SERVICES; do
          REPO_NAME="$PROJECT_NAME-$service"
          IMAGE_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"
          echo "Building Docker image for $service..."
          docker build -t "$IMAGE_URI" -f "microservices/$service/Dockerfile" "microservices/$service"
          echo "Pushing Docker image for $service to $IMAGE_URI..."
          docker push "$IMAGE_URI"
        done
  post_build:
    commands:
      - echo Build completed on `date`

# No artifacts are needed for this pipeline design
