version: '3.8'
services:
  cart-db:
    image: postgres:13
    container_name: cart-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cart-db
    volumes:
      - cart-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:13
    container_name: order-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order-db
    volumes:
      - order-db-data:/var/lib/postgresql/data

  product-db:
    image: postgres:13
    container_name: product-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product-db
    volumes:
      - product-db-data:/var/lib/postgresql/data

  summary-db:
    image: postgres:13
    container_name: summary-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: summary-db
    volumes:
      - summary-db-data:/var/lib/postgresql/data

volumes:
  cart-db-data:
  order-db-data:
  product-db-data:
  summary-db-data: 