-- Cart service baseline schema. Mirrors the Hibernate-managed schema so that
-- the service can start with spring.jpa.hibernate.ddl-auto=validate.
CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL
);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price DOUBLE PRECISION,
    product_id BIGINT,
    product_name VARCHAR(255),
    quantity INTEGER
);

-- Unidirectional one-to-many collection table owning Cart.items.
CREATE TABLE cart_items (
    cart_id BIGINT NOT NULL,
    items_id BIGINT NOT NULL,
    CONSTRAINT uk_cart_items_items UNIQUE (items_id)
);