version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0
  pre_build:
    commands:
      - cd terraform
      - |
        terraform init \
          -backend-config="bucket=${TF_BACKEND_BUCKET}" \
          -backend-config="key=${TF_BACKEND_KEY}" \
          -backend-config="region=${TF_BACKEND_REGION}" \
          -backend-config="dynamodb_table=${TF_BACKEND_DYNAMODB_TABLE}" \
          -backend-config="encrypt=true"
  build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -input=false tfplan

