version: 0.2

phases:
  install:
    commands:
      - echo "Preparing smoke test runner"
  build:
    commands:
      - chmod +x scripts/post-deploy-smoke.sh
      - ./scripts/post-deploy-smoke.sh

reports:
  smoke-results:
    files:
      - '**/*.log'
