version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0
  pre_build:
    commands:
      - cd terraform
      - |
        WORKSPACE=${TF_WORKSPACE:-dev}
        terraform init
        terraform workspace select "${WORKSPACE}" || terraform workspace new "${WORKSPACE}"
  build:
    commands:
      - echo "Applying Terraform plan..."
      - terraform apply -input=false tfplan

