spring.datasource.url=jdbc:h2:mem:cart-test-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
server.port=8080
# server.address=localhost
jwt.secret=${random.uuid}
services.product.base-url=${PRODUCT_SERVICE_BASE_URL:http://product-service:8080}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Observability
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

# Structured Logging
logging.pattern.console={"time": "%d{yyyy-MM-dd HH:mm:ss.SSS}", "level": "%level", "thread": "%thread", "logger": "%logger", "message": "%message"}%n
