-- Order service baseline schema. Mirrors the Hibernate-managed schema so that
-- the service can start with spring.jpa.hibernate.ddl-auto=validate.
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT,
    idempotency_key VARCHAR(255),
    order_date TIMESTAMP(6),
    status VARCHAR(255),
    total DOUBLE PRECISION,
    user_id VARCHAR(255)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_orders_status ON orders (status);
-- Order idempotency: repeated checkouts with the same key return the original order.
CREATE UNIQUE INDEX uk_orders_user_idempotency ON orders (user_id, idempotency_key);

-- Embedded collection table owning Order.orderLines.
CREATE TABLE order_lines (
    order_id BIGINT NOT NULL,
    line_total DOUBLE PRECISION NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL
);

-- Kafka outbox for order-created events.
CREATE TABLE order_event_store (
    id UUID PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_until TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL,
    last_error VARCHAR(500)
);

CREATE INDEX idx_order_event_store_status_created ON order_event_store (status, created_at);
CREATE INDEX idx_order_event_store_status_retry ON order_event_store (status, next_attempt_at);