spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://order-db:5432/grocery}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:grocellery}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8080
services.cart.base-url=${CART_SERVICE_BASE_URL:http://cart-service:8080}
services.cart.connect-timeout-ms=${CART_SERVICE_CONNECT_TIMEOUT_MS:2000}
services.cart.read-timeout-ms=${CART_SERVICE_READ_TIMEOUT_MS:3000}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
app.kafka.topics.order-created=${KAFKA_ORDER_CREATED_TOPIC:order.created.v1}
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.delivery.timeout.ms=30000
spring.kafka.admin.fail-fast=true

jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
logging.pattern.console={"time":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","thread":"%thread","logger":"%logger","message":"%message"}%n
