spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
server.port=${SERVER_PORT:8080}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.retries=${KAFKA_PRODUCER_RETRIES:3}
spring.kafka.producer.properties.delivery.timeout.ms=${KAFKA_DELIVERY_TIMEOUT_MS:30000}
app.kafka.topics.order-created=${KAFKA_ORDER_CREATED_TOPIC:order.created.v1}

jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
logging.pattern.console={"time":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","thread":"%thread","logger":"%logger","message":"%message"}%n
