-- Summary service baseline schema. Mirrors the Hibernate-managed schema so that
-- the service can start with spring.jpa.hibernate.ddl-auto=validate.
CREATE TABLE summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    order_id BIGINT NOT NULL,
    total_amount NUMERIC(38,2),
    item_count INTEGER,
    created_at TIMESTAMP(6),
    details VARCHAR(255)
);

CREATE INDEX idx_summary_user_id ON summary (user_id);
CREATE INDEX idx_summary_order_id ON summary (order_id);
CREATE UNIQUE INDEX uk_summary_order_id ON summary (order_id);

-- Consumer idempotency log for applied order-created events.
CREATE TABLE processed_order_events (
    event_id VARCHAR(255) PRIMARY KEY,
    processed_at TIMESTAMP(6)
);