-- Product service baseline schema. Mirrors the Hibernate-managed schema so that
-- the service can start with spring.jpa.hibernate.ddl-auto=validate.
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price DOUBLE PRECISION,
    available BOOLEAN DEFAULT TRUE NOT NULL,
    stock_quantity INTEGER NOT NULL,
    image_url VARCHAR(255)
);

CREATE INDEX idx_product_name ON product (name);