-- Idempotent stock reservations for checkout. Mirrors the Hibernate-managed
-- schema so the service can start with spring.jpa.hibernate.ddl-auto=validate.
CREATE TABLE stock_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_key VARCHAR(255) NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    released_at TIMESTAMP
);

CREATE UNIQUE INDEX idx_stock_reservation_key ON stock_reservation (reservation_key);